controller:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/vultr-loadbalancer-protocol: "tcp"
      service.beta.kubernetes.io/vultr-loadbalancer-label: "staging-ingress"
